---
title: "Ch 5 — Bayes"
author: "Mike Dietze"
date: "May 5, 2015"
output: html_document
---

## Likelihood

Which hypothesis is more likely?

```{r}
curve(dnorm(x,0,0.7),-1,4,ylab="Density",lwd=4)
curve(dnorm(x,3,1.3),-1,4,lwd=4,col="orange",add=TRUE)
abline(v=c(0,1.5,3),col=c(1,"blue","orange"),lwd=3,lty=2)
mtext(c("H1","data","H2"),3,at=c(0,1.5,3),cex=1.5,col=c(1,"blue","orange"))

L = dnorm(1.5,c(0,3),c(0.7,1.3))
L
L[2]/L[1]
```


log likelihood profile
```{r}
x = seq(-1,4,length=1000)
lnL = -dnorm(1.5,x,1,log=TRUE)
plot(x,lnL,ylab="-ln(L)",cex.lab=1.5,xlab=expression(mu),type='l',lwd=4)
abline(v=1.5,col="blue",lwd=3,lty=2)
```

Monte Carlo Concept
```{r}
n = signif(10^(seq(0.5,5,length=4)),digits=1)
par(mfrow=c(1,4))
for(i in 1:4){
  x = rnorm(n[i])
  hist(x,probability=TRUE,xlim=c(-4,4),ylim=c(0,0.5),
       main=paste("N =",format(n[i],scientific=FALSE)),cex.main=1.5,cex.lab=1.2)
  curve(dnorm(x),-4,4,add=TRUE,lwd=3)
#  abline(v=c(mean(x),quantile(x,c(0.025,0.975))),lty=2,lwd=3)
  vals = format(round(c(mean(x),quantile(x,c(0.025,0.975))),digits=2),scientific=FALSE)
  text(x = -3,y = 0.5,pos = 4,
       labels = paste0(vals[1],
       " (",vals[2],",",vals[3],")"),cex=1.5)
  
}
```

Simple MCMC
```{r}
nMC = 10000  ## number of MC iterations
x = 1.5   ## data
sd = 1    ## assume a known mean
mu = numeric(nMC) ## storage
mu[1]=x   ## initial condition
Jsd = 2   ## jump standard deviation
mu.p = 0  ## prior mean
sd.p = 1e6 ## prior Standard deviation
for(i in 2:nMC){
  #propose new value
  muStar = rnorm(1,mu[i-1],Jsd)
  #posterior at new point = L*prior
  pStar  = dnorm(x,muStar,sd,log=TRUE)+dnorm(muStar,mu.p,sd.p,log=TRUE)
  #posterior at current point
  pC     = dnorm(x,mu[i-1],sd,log=TRUE)+dnorm(mu[i-1],mu.p,sd.p,log=TRUE)
  ## acceptance criteria
  if(exp(pStar-pC)>runif(1)){
    # accept
    mu[i] = muStar
  } else {
    mu[i] = mu[i-1]
  }
}
#```

#Basic MCMC diagnostics
#```{r}
library(coda)
mu2 = as.mcmc(mu)
plot(mu2)
summary(mu2)
1-rejectionRate(mu2)
effectiveSize(mu2)
par(mfrow=c(1,2))
plot(mu[nMC-(1000:1)],type='l',ylab="mu",xlab="MCMC Sample")
#plot(density(mu,adjust=1.5),lwd=3,main="Posterior")
#abline(h=0)
hist(mu,probability=TRUE,main="Posterior")
abline(v=quantile(mu,c(0.025,0.5,0.975)),lty=c(2,1,2),lwd=c(1.5,3,1.5))
```


Burn-in
```{r}
nMC = 10000  ## number of MC iterations
x = 1.5   ## data
sd = 1    ## assume a known mean
mu = matrix(0,3,nMC) ## storage
mu[,1]=c(20,0,-20)   ## initial condition
Jsd = .5   ## jump standard deviation
mu.p = 0  ## prior mean
sd.p = 1e6 ## prior Standard deviation
for(i in 2:nMC){
  #propose new value
  muStar = rnorm(3,mu[,i-1],Jsd)
  #posterior at new point = L*prior
  pStar  = dnorm(x,muStar,sd,log=TRUE)+dnorm(muStar,mu.p,sd.p,log=TRUE)
  #posterior at current point
  pC     = dnorm(x,mu[,i-1],sd,log=TRUE)+dnorm(mu[,i-1],mu.p,sd.p,log=TRUE)
  ## acceptance criteria
  z = exp(pStar-pC)>runif(1) 
  mu[z,i] = muStar[z]
  mu[!z,i] = mu[!z,i-1]
}

thr = 200 #max(apply(mu,1,function(mu){which(abs(mu-median(mu[1000:Nmc]))<0.01)[1]})) #threshold

plot(0,0,type='n',xlim=c(1,3*thr),ylim=range(mu),ylab="mu",xlab="MCMC Sample",main="Trace Plot")
for(i in 1:3){
  lines(mu[i,],col=i,lwd=2)
}
abline(h=quantile(mu[,1000:Nmc],c(0.025,0.5,0.975)),lwd=2,lty=c(3,1,3))
abline(v=thr,lty=2,lwd=3)
text(thr*0.6,13,"BURN-IN",srt=90,cex=1.5,pos=1)

mu2 = list()
for(i in 1:3){mu2[[i]]=as.mcmc(mu[i,])}
mu2=as.mcmc.list(mu2)
plot(mu2)
gbr <- gelman.plot(mu2,max.bins=500)
plot(gbr$last.iter,gbr$shrink[,1,1],type='l',xlim=c(1,3*thr),lwd=3,ylab="log(Shrink)",xlab="MCMC Sample",log='y',main="GBR Diagnostic")
abline(h=c(1,1.1),lty=1:2)
abline(v=thr,lty=2,lwd=3)
text(50,3,"BURN-IN",srt=90,cex=1.5,pos=1)

## Remove burnin
mu3 = list()
for(i in 1:3){mu3[[i]]=as.mcmc(mu[i,-(1:1000)])}
mu3=as.mcmc.list(mu3)
densityplot(mu3)
densplot(mu3)
levelplot(mu3)
acfplot(mu3)
autocorr.plot(mu3)

#plot(acf(mu,40))
```


BANANA

Code modified from Florian Hartig
Cited as having come from example from Meng and Barnard &code from the bayesm package

```{r}

banana=function(A,B,C1,C2,N,keep=10,init=10)
{
    R=init*keep+N*keep
    x1=x2=0
    bimat=matrix(double(2*N),ncol=2)
    for (r in 1:R) {
        x1=rnorm(1,mean=(B*x2+C1)/(A*(x2^2)+1),sd=sqrt(1/(A*(x2^2)+1)))
        x2=rnorm(1,mean=(B*x2+C2)/(A*(x1^2)+1),sd=sqrt(1/(A*(x1^2)+1)))
        if (r>init*keep && r%%keep==0) {
            mkeep=r/keep; bimat[mkeep-init,]=c(x1,x2)
        }
    }

    return(bimat)
}
A=0.5; B=0; C1=C2=3
sample=banana(A=A,B=B,C1=C1,C2=C2,50000)
```

```{r}
## modified original smoothScatter to return matrix
smoothScatter2 = function (x, y = NULL, nbin = 128, bandwidth, colramp = colorRampPalette(c("white", 
    blues9)), nrpoints = 100, pch = ".", cex = 1, col = "black", 
    transformation = function(x) x^0.25, postPlotHook = box, 
    xlab = NULL, ylab = NULL, xlim, ylim, xaxs = par("xaxs"), 
    yaxs = par("yaxs"), ...) 
{
    if (!is.numeric(nrpoints) | (nrpoints < 0) | (length(nrpoints) != 
        1)) 
        stop("'nrpoints' should be numeric scalar with value >= 0.")
    xlabel <- if (!missing(x)) 
        deparse(substitute(x))
    ylabel <- if (!missing(y)) 
        deparse(substitute(y))
    xy <- xy.coords(x, y, xlabel, ylabel)
    xlab <- if (is.null(xlab)) 
        xy$xlab
    else xlab
    ylab <- if (is.null(ylab)) 
        xy$ylab
    else ylab
    x <- cbind(xy$x, xy$y)[is.finite(xy$x) & is.finite(xy$y), 
        , drop = FALSE]
    if (!missing(xlim)) {
        stopifnot(is.numeric(xlim), length(xlim) == 2, is.finite(xlim))
        x <- x[min(xlim) <= x[, 1] & x[, 1] <= max(xlim), ]
    }
    else {
        xlim <- range(x[, 1])
    }
    if (!missing(ylim)) {
        stopifnot(is.numeric(ylim), length(ylim) == 2, is.finite(ylim))
        x <- x[min(ylim) <= x[, 2] & x[, 2] <= max(ylim), ]
    }
    else {
        ylim <- range(x[, 2])
    }
    map <- grDevices:::.smoothScatterCalcDensity(x, nbin, bandwidth)
    xm <- map$x1
    ym <- map$x2
    dens <- map$fhat
    dens[] <- transformation(dens)
    image(xm, ym, z = dens, col = colramp(256), xlab = xlab, 
        ylab = ylab, xlim = xlim, ylim = ylim, xaxs = xaxs, yaxs = yaxs, 
        ...)
    if (!is.null(postPlotHook)) 
        postPlotHook()
    if (nrpoints > 0) {
        nrpoints <- min(nrow(x), ceiling(nrpoints))
        stopifnot((nx <- length(xm)) == nrow(dens), (ny <- length(ym)) == 
            ncol(dens))
        ixm <- 1L + as.integer((nx - 1) * (x[, 1] - xm[1])/(xm[nx] - 
            xm[1]))
        iym <- 1L + as.integer((ny - 1) * (x[, 2] - ym[1])/(ym[ny] - 
            ym[1]))
        sel <- order(dens[cbind(ixm, iym)])[seq_len(nrpoints)]
        points(x[sel, ], pch = pch, cex = cex, col = col)
    }
    return(list(x=xm,y=ym,z=dens))
}

Mode <- function(x){
  d = density(x)
  d$x[which.max(d$y)]
}

scatterhist = function(x, y, xlab="", ylab="", smooth = TRUE){
  zones=matrix(c(2,0,1,3), ncol=2, byrow=TRUE)
  layout(zones, widths=c(4/5,1/5), heights=c(1/5,4/5))
  xhist = hist(x, plot=FALSE, breaks = 50)
  yhist = hist(y, plot=FALSE, breaks = 50)
  top = max(c(xhist$counts, yhist$counts))
  par(mar=c(3,3,1,1))
  if (smooth == TRUE) {
    ss = smoothScatter2(x,y, colramp = colorRampPalette(c("white", "darkorange", "darkred", "darkslateblue")),
                  xlim=range(xhist$breaks),ylim=range(yhist$breaks))
    mc = apply(ss$z,2,which.max)
    mr = apply(ss$z,1,which.max)
    mz = which.max(ss$z[cbind(mr,mc)])
    mode = c(ss$x[mc[mz]],ss$y[mr[mz]])
  }else{ plot(x,y)}
  
  abline(h=Mode(y),lty=2,lwd=3)
  abline(v=Mode(x),lty=2,lwd=3)
  points(mode[1],mode[2],cex=3,pch="+")
  par(mar=c(0,3,1,1))
#  barplot(xhist$counts, axes=FALSE, ylim=c(0, top), space=0)
#  hist(x,axes=FALSE,main=" ")
 plot(NULL, type = "n", ylim = c(0,max(xhist$counts)), xlim = c(range(xhist$breaks)),axes=FALSE)
    rect(xhist$breaks[1:(length(xhist$breaks) - 1)], 0, xhist$breaks[2:length(xhist$breaks)], xhist$counts)
    abline(v=Mode(x),lty=2,lwd=3)
  par(mar=c(3,0,1,1))
  #barplot(yhist$counts, axes=FALSE, xlim=c(0, top), space=0, horiz=TRUE)
  plot(NULL, type = "n", xlim = c(0, max(yhist$counts)), ylim = c(range(yhist$breaks)),axes=FALSE)
    rect(0, yhist$breaks[1:(length(yhist$breaks) - 1)], yhist$counts, yhist$breaks[2:length(yhist$breaks)])
    abline(h=Mode(y),lty=2,lwd=3)
  par(oma=c(3,3,0,0))
  mtext(xlab, side=1, line=1, outer=TRUE, adj=0, 
        at=.8 * (mean(x) - min(x))/(max(x)-min(x)))
  mtext(ylab, side=2, line=1, outer=TRUE, adj=0, 
        at=(.8 * (mean(y) - min(y))/(max(y) - min(y))))
}

scatterhist(sample[,1], sample[,2])


```

